$:
  tag_push: &build
    - env:
        DOCKER_LATEST_TAG: mirrors.tencent.com/standards/golangci-lint-tencent:latest
        DOCKER_COMMIT_TAG: mirrors.tencent.com/standards/golangci-lint-tencent:$ORANGE_COMMIT_SHORT
        DOCKER_TAG: mirrors.tencent.com/standards/golangci-lint-tencent:$ORANGE_BRANCH
      services:
        - docker
      stages:
        - name: docker build
          script: docker build -t $DOCKER_COMMIT_TAG -t $DOCKER_LATEST_TAG -t $DOCKER_TAG -f docker/Dockerfile .
        - name: docker login
          script: docker login -u $DOCKER_USER -p $DOCKER_PWD mirrors.tencent.com
          envFrom: https://git.woa.com/orange-secret/orange-ci-config/blob/master/envs/g-orangeci.yml
        - name: push image
          script:
            - docker push $DOCKER_LATEST_TAG
            - docker push $DOCKER_COMMIT_TAG
            - docker push $DOCKER_TAG

master:
  push: *build

  merge_request:
    - services:
        - docker
      stages:
        - name: docker build
          script: docker build -f docker/Dockerfile -t lint:tmp .
        - name: lint by docker
          script:
            - docker run -v ./tencentlint:/code -w /code --rm -ePLUGIN_EXTRA_ARGS=-v lint:tmp
            - docker run -v ./cmd/tencentlint:/code -w /code --rm -ePLUGIN_EXTRA_ARGS=-v lint:tmp
    - docker:
        image: golang:1.23
      services:
        - ssh-agent-for-oa
      stages:
        - name: lint by cmd
          script:
            - cd ./cmd/tencentlint && go build && cd -
            - cd ./tencentlint && ../cmd/tencentlint/tencentlint -verbose --plugin-path ./ run -c ../.golangci.yml && cd -
            - cd ./cmd/tencentlint/ && ./tencentlint -verbose --plugin-path ../../tencentlint run -c ../../.golangci.yml && cd -
