openapi: 3.0.0

info:
  title: {{apiTitle}}
  description: {{apiDescription}}
  version: {{apiVersion}}
  contact:
    name: {{contactName}}
    email: {{contactEmail}}
  license:
    name: {{licenseName}}
    url: {{licenseUrl}}

servers:
  - url: {{productionUrl}}
    description: 生产环境
  - url: {{stagingUrl}}
    description: 测试环境
  - url: {{developmentUrl}}
    description: 开发环境

tags:
  - name: {{tag1Name}}
    description: {{tag1Description}}
  - name: {{tag2Name}}
    description: {{tag2Description}}

paths:
  {{endpoint1Path}}:
    {{endpoint1Method}}:
      summary: {{endpoint1Summary}}
      description: {{endpoint1Description}}
      tags:
        - {{endpoint1Tag}}
      operationId: {{endpoint1OperationId}}
      parameters:
        - name: {{param1Name}}
          in: {{param1In}}
          description: {{param1Description}}
          required: {{param1Required}}
          schema:
            type: {{param1Type}}
      requestBody:
        required: {{endpoint1RequestBodyRequired}}
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/{{endpoint1RequestSchema}}'
            example:
              {{endpoint1RequestExample}}
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/{{endpoint1ResponseSchema}}'
              example:
                {{endpoint1ResponseExample}}
        '400':
          description: 请求参数错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: 未授权
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 禁止访问
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 资源不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 服务器内部错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []
      x-code-samples:
        - lang: curl
          source: |
            curl -X {{endpoint1Method}} {{productionUrl}}{{endpoint1Path}} \
              -H "Authorization: Bearer YOUR_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{{endpoint1RequestExample}}'
        - lang: javascript
          source: |
            const response = await fetch('{{productionUrl}}{{endpoint1Path}}', {
              method: '{{endpoint1Method}}',
              headers: {
                'Authorization': 'Bearer YOUR_TOKEN',
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({{endpoint1RequestExample}})
            });
            const data = await response.json();

  {{endpoint2Path}}:
    {{endpoint2Method}}:
      summary: {{endpoint2Summary}}
      description: {{endpoint2Description}}
      tags:
        - {{endpoint2Tag}}
      operationId: {{endpoint2OperationId}}
      parameters:
        - name: {{param2Name}}
          in: {{param2In}}
          description: {{param2Description}}
          required: {{param2Required}}
          schema:
            type: {{param2Type}}
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/{{endpoint2ResponseSchema}}'
        '404':
          description: 资源不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: 错误码
          example: "ERR_INVALID_REQUEST"
        message:
          type: string
          description: 错误信息
          example: "请求参数错误"
        details:
          type: object
          description: 错误详情
          additionalProperties: true

    {{endpoint1RequestSchema}}:
      type: object
      required:
        - {{requiredField1}}
        - {{requiredField2}}
      properties:
        {{field1Name}}:
          type: {{field1Type}}
          description: {{field1Description}}
          example: {{field1Example}}
        {{field2Name}}:
          type: {{field2Type}}
          description: {{field2Description}}
          example: {{field2Example}}
        {{field3Name}}:
          type: {{field3Type}}
          description: {{field3Description}}
          example: {{field3Example}}

    {{endpoint1ResponseSchema}}:
      type: object
      properties:
        code:
          type: string
          description: 响应码
          example: "SUCCESS"
        message:
          type: string
          description: 响应信息
          example: "操作成功"
        data:
          type: object
          description: 响应数据
          properties:
            {{responseField1}}:
              type: {{responseField1Type}}
              description: {{responseField1Description}}
            {{responseField2}}:
              type: {{responseField2Type}}
              description: {{responseField2Description}}

    {{endpoint2ResponseSchema}}:
      type: object
      properties:
        code:
          type: string
          example: "SUCCESS"
        message:
          type: string
          example: "操作成功"
        data:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              createdAt:
                type: string
                format: date-time

    PaginationResponse:
      type: object
      properties:
        code:
          type: string
          example: "SUCCESS"
        message:
          type: string
          example: "操作成功"
        data:
          type: array
          items:
            type: object
        pagination:
          type: object
          properties:
            page:
              type: integer
              example: 1
            pageSize:
              type: integer
              example: 20
            total:
              type: integer
              example: 100
            totalPages:
              type: integer
              example: 5

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT 认证令牌

  parameters:
    PageParam:
      name: page
      in: query
      description: 页码（从 1 开始）
      required: false
      schema:
        type: integer
        default: 1
        minimum: 1

    PageSizeParam:
      name: pageSize
      in: query
      description: 每页数量
      required: false
      schema:
        type: integer
        default: 20
        minimum: 1
        maximum: 100

    SortParam:
      name: sort
      in: query
      description: 排序字段和方向（例如：-createdAt 表示按创建时间倒序）
      required: false
      schema:
        type: string

x-api-info:
  baseUrl: {{productionUrl}}
  authentication: JWT Bearer Token
  rateLimit:
    requests: {{rateLimitRequests}}
    window: {{rateLimitWindow}}
  timeout: {{apiTimeout}}
  retryPolicy:
    maxRetries: {{maxRetries}}
    backoffMultiplier: {{backoffMultiplier}}

x-error-codes:
  ERR_INVALID_REQUEST:
    httpStatus: 400
    message: 请求参数错误
    description: 请求参数格式不正确或缺少必需参数

  ERR_UNAUTHORIZED:
    httpStatus: 401
    message: 未授权
    description: 缺少有效的认证令牌

  ERR_FORBIDDEN:
    httpStatus: 403
    message: 禁止访问
    description: 用户没有权限访问该资源

  ERR_NOT_FOUND:
    httpStatus: 404
    message: 资源不存在
    description: 请求的资源不存在

  ERR_CONFLICT:
    httpStatus: 409
    message: 冲突
    description: 请求与当前状态冲突

  ERR_INTERNAL_SERVER_ERROR:
    httpStatus: 500
    message: 服务器内部错误
    description: 服务器处理请求时发生错误

  ERR_SERVICE_UNAVAILABLE:
    httpStatus: 503
    message: 服务不可用
    description: 服务暂时不可用，请稍后重试

x-changelog:
  - version: {{version1}}
    date: {{version1Date}}
    changes:
      - {{version1Change1}}
      - {{version1Change2}}
  - version: {{version2}}
    date: {{version2Date}}
    changes:
      - {{version2Change1}}
