master:
  review:
    -
      stages:
        - name: CR 通过后自动合并
          type: git:automerge
          options:
            mergeType: squash
            mergeCommitMessage: $ORANGE_LATEST_COMMIT_MESSAGE
          exports:
            reviewedBy: REVIEWED_BY
        - name: notify
          type: wework:message
          imports: https://git.woa.com/standards/secrets/blob/master/reviewer-java.yml
          options:
            robot: $robot
            message: |
              > CR 通过后自动合并 <@${ORANGE_BUILD_USER}> 
              > 　
              > ${ORANGE_MERGE_REQUEST_TITLE}
              > [${ORANGE_EVENT_URL}](${ORANGE_EVENT_URL})
              > 
              > ${REVIEWED_BY}
  push:
    - stages:
        - name: Auto Tag
          type: git:autotag
  merge_request:
    - stages:
        - name: CheckStyle
          image: mirrors.tencent.com/standards/checkstyle-tencent:latest
          settings:
            format: plain

        - name: add reviewer
          type: git:review
          imports: https://git.woa.com/standards/secrets/blob/master/reviewer-java.yml
          options:
            reviewers: $reviewers
            count: 2
          exports:
            reviewersForAt: CURR_REVIEWER_FOR_AT
        - name: notify
          type: wework:message
          imports: https://git.woa.com/standards/secrets/blob/master/reviewer-java.yml
          options:
            robot: $robot
            message: |
              > ${CURR_REVIEWER_FOR_AT}
              > 　
              > ${ORANGE_MERGE_REQUEST_TITLE}
              > [${ORANGE_EVENT_URL}](${ORANGE_EVENT_URL})
              > 　
              > from ${ORANGE_BUILD_USER}
$:
  tag_push:
    - runner:
        network: idc-hk
      env:
        DOCKER_LATEST_TAG_CSIG: csighub.tencentyun.com/standards/checkstyle-tencent:latest
        DOCKER_TAG_CSIG: csighub.tencentyun.com/standards/checkstyle-tencent:$ORANGE_BRANCH
        DOCKER_LATEST_TAG: mirrors.tencent.com/standards/checkstyle-tencent:latest
        DOCKER_TAG: mirrors.tencent.com/standards/checkstyle-tencent:$ORANGE_BRANCH
      services:
        - docker
      stages:
        - name: docker build
          script: cd checkstyle && docker build -t $DOCKER_LATEST_TAG_CSIG -t $DOCKER_TAG_CSIG -t $DOCKER_LATEST_TAG -t $DOCKER_TAG .
        - name: docker login mirrors
          envFrom: https://git.woa.com/orange-secret/orange-ci-config/blob/master/envs/g-orangeci.yml
          script: docker login -u $DOCKER_USER -p $DOCKER_PWD mirrors.tencent.com
        - name: docker push
          script: 
            - docker push $DOCKER_LATEST_TAG
            - docker push $DOCKER_TAG

        - name: docker login csig
          envFrom: https://git.woa.com/standards/secrets/blob/master/docker-image.txt
          script: docker login -u $DOCKER_USER -p $DOCKER_PWD csighub.tencentyun.com
        - name: docker push
          script: 
            - docker push $DOCKER_LATEST_TAG_CSIG 
            - docker push $DOCKER_TAG_CSIG

